In [8]:
import numpy as np
import time
from functools import reduce

In [6]:
a = np.array([1,2,3])
print("Tile:", np.tile(a,2))
print("Repeat:", np.repeat(a,2))

Tile: [1 2 3 1 2 3]
Repeat: [1 1 2 2 3 3]


In [ ]:
# Copii intre ndarrays + referinte
b = a #Shallow = partajeaza aceiasi adresa de memorie
c = a.copy() # Deep copy: Se aloca o zona noua de memorie
b[0] = 10
c[0] = 20
print(b,c)

10 20


In [ ]:
#Performanta in numpy

In [ ]:
start_opeartie_numpy = time.time()
a = np.arange(1,1_000_001) #1_000_001 <=> 1.000.001 (la nivel conceptual)
a_squared = a**2
durata_operartie_numpy = time.time() - start_opeartie_numpy


start_lista = time.time()

lst = [i **2 for i in range(1,1000001)]
#lst_sqare = [i**2 for i in lst]
durata_operartie_lista = time.time() - start_lista

print("Comparatie in termeni de performanta")
print(f"Timp numpy: {durata_operartie_numpy:.5f}")
print(f"Timp lista: {durata_operartie_lista:.5f}")
print(f"Delta: {durata_operartie_numpy-durata_operartie_lista:.5f}")
# Testele de performanta
# Ne uitam la timpul de exectutie pe acelasi test rulat de cateva mii de ori
# si faci o medie a timpului iteratiilor
# Ne uitam si la loading-ul din memorie

Comparatie in termeni de performanta
Timp numpy: 0.00982
Timp lista: 0.65062
Delta: -0.64080


In [ ]:
#broadcasting si operatii pe ndarrays
# broadcasting = modalitatea prin care numpy rezolva operatii intre ndarrays
# print extinderea automata a ndarray-ului de forma mai mica a.i. acesta sa se 
# potriveasca celui mare

c = np.array([
    [1,2,3],
    [4,5,6]
])
print("Broadcasting de elemente:\n",c*2) # inmultire cu un scalar

x = np.array([
    [1,2],
    [3,4]
])

y = np.array([
    [2,2],
    [2,2]
])

print("inmultire elemente cu element: \n",  x * y)

print("Multiplcicare matriceala: \n",x@y)
#Echivalent
print("multiplicare cu numpy:\n",np.dot(x,y))


a = np.array([
    [1,2],
    [3,4],
    [5,6]
])

b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a*b)

Broadcasting de elemente:
 [[ 2  4  6]
 [ 8 10 12]]
inmultire elemente cu element: 
 [[2 4]
 [6 8]]
Multiplcicare matriceala: 
 [[ 6  6]
 [14 14]]
multiplicare cu numpy:
 [[ 6  6]
 [14 14]]
